<?php
include "funcs.php";
start();

?>
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="css/style.css">
		<title>Exam Generator - All Exams List.</title>
	</head>
	<body>
		<?php include "header.php" ?>
		<br><br>

		<div class="wide-table res-ico">
			<h2><i class="fa fa-archive"></i> Manually Created Assignment/Exams</h2>
			<br>
			<table id="tabler">
				<thead>
					<th>Title</th>
					<th>Creation Date</th>
					<th>Course</th>
					<th>Created By</th>
				</thead>
				<tbody>
					<?php
						$res = $db->query("SELECT * FROM Exam_Manual Order By DateTime DESC");
						if(mysqli_num_rows($res)){
							while($row = $res->fetch_assoc()){								
								$course = $db->query("SELECT * FROM Course WHERE CourseID = ". $row["CourseID"])->fetch_assoc();
								$user = $db->query("SELECT * FROM user WHERE UserID = ". $row["UserID"])->fetch_assoc();
								printf("<tr><td><a href='exam_preview_man.php?e=%d'>%s</a></td><td>%s</td><td>%s</td><td>%s</td></tr>",
									$row["ExamID"],
									$row["ExamTitle"],
									$row["DateTime"],
									htmlspecialchars($course["CourseString"]),
									htmlspecialchars($user["Name"])
								);
							}
						}
						else echo "No Exams";
					?>
				</tbody>
			</table>
			<br><br>
		</div><br><br>

		<div class="wide-table res-ico">
			<h2><i class="fa fa-cog"></i> Generated Exams</h2>
			<br>
			<table id="tablee">
				<thead>
					<th>Generated Date</th>
					<th>Course</th>
					<th>Generated By</th>
				</thead>
				<tbody>
					<?php
						$res = $db->query("SELECT * FROM Exam Order By DateTime DESC");
						if(mysqli_num_rows($res)){
							while($row = $res->fetch_assoc()){								
								$course = $db->query("SELECT * FROM Course WHERE CourseID = ". $row["CourseID"])->fetch_assoc();
								$user = $db->query("SELECT * FROM user WHERE UserID = ". $row["UserID"])->fetch_assoc();
								printf("<tr><td><a href='exam_preview.php?e=%d'>%s</a></td><td>%s</td><td>%s</td></tr>",
									$row["ExamID"],
									$row["DateTime"],
									htmlspecialchars($course["CourseString"]),
									htmlspecialchars($user["Name"])
								);
							}
						}
						else echo "No Exams";
					?>
				</tbody>
			</table>
			<br><br>
		</div><br>
		<script src="lib/jquery.min.js"></script>
		<script src="lib/jquery-paginate.min.js"></script>
		<script type="text/javascript">
			$('#tablee').paginate({ limit: 10});
			$('#tabler').paginate({ limit: 10});
		</script>
		<?php include "footer.php" ?>
	</body>
</html>